# Change these first
owner: amblerkr # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: ambler.kr
    url: https://ambler.kr/
  - name: notion.ambler.kr
    url: https://notion.ambler.kr/
  - name: fruition.ambler.kr
    url: https://fruition.ambler.kr/
  - name: parkjuhyun.kr
    url: https://parkjuhyun.kr/
  - name: loona.kr
    url: https://loona.kr/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.ambler.kr
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** for Ambler"
  introMessage: 공연과 음악을 좋아하는 크리에이터, Ambler 😎
