# Change these first
owner: amblerkr # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: ambler.kr
    url: https://ambler.kr/
  - name: link.ambler.kr
    url: https://link.ambler.kr/
  - name: notion.ambler.kr
    url: https://notion.ambler.kr/
  - name: fruition.ambler.kr
    url: https://fruition.ambler.kr/
  - name: chatwoot.ambler.kr
    url: https://chatwoot.ambler.kr/
  - name: svg-to-png.ambler.kr
    url: https://svg-to-png.ambler.kr/
  - name: rsshub.ambler.kr
    url: https://rsshub.ambler.kr/
  - name: rssbox.ambler.kr
    url: https://rssbox.ambler.kr/
  - name: rssbridge.ambler.kr
    url: https://rssbridge.ambler.kr/  
  - name: reddit-rss.ambler.kr
    url: https://reddit-rss.ambler.kr/
  - name: tiktokrss.ambler.kr
    url: https://tiktokrss.ambler.kr/   
  - name: monitorss.ambler.kr
    url: https://monitorss.ambler.kr/
  - name: bluv.ambler.kr
    url: https://bluv.ambler.kr/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: upptime.ambler.kr
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** for Ambler"
  introMessage: 공연과 음악을 좋아하는 크리에이터, Ambler 😎
